### ISSUE TITLE
[@hono/vite-cloudflare-pages] Serve static assets using `_routes.json`

### ISSUE THREAD

**Issue by akku1139** [honojs/vite-plugins#110]
It is currently using `serveStatic()` ( `env.ASSETS.fetch()` ) to serve static assets in Cloudflare Pages, but there are some issues with this.

1. Consume function requests number of times.

The number of function calls is consumed because the function is executed every time there is a request for an asset.
However, access to static assets is unlimited.

![image](https://github.com/honojs/vite-plugins/assets/151517253/c3ca3eb3-99c3-4010-9af2-629d745ed734)
> The Free plan combines requests for Workers and Pages Functions. Requests to static assets on Pages will continue to be free and unlimited.

2. Asset access is slow.

Cloudflare Page Functions are fast enough, but there is some overhead compared to direct asset access.

Therefore, I think it needs to serve assets using `_routes.json`.
https://developers.cloudflare.com/pages/functions/routing/#create-a-_routesjson-file

```json
{
  "version": 1,
  "include": ["/*"],
  "exclude": [
    "/static/*",
    "/favicon.ico"
  ]
}
```

**Comment by nakasyou** [comment]
I think generating `_routes.json` is good solution.

What do you think about exporting middleware that telling hint to generating?

For example,
```ts
import { serveStatic } from '@hono/vite-cloudflare-pages'

app.get('/*', serveStatic({ .. }))
```
When in develop mode, this middleware works same as normal `serveStatic` middleware.
When plugin builds, this middleware give plugin the hint of generating `_routes.json`.

**Comment by yudai-nkt** [comment]
This issue is something I once considered submitting but forgot. I'd like to have this feature as well and wrote a naive Vite plugin for this in one of my projects: https://github.com/yudai-nkt/awesome-hono/blob/main/vite-plugins/auto-exclude-static-routes.ts. I hope this will serve as a sort of good starting point.
