### ISSUE TITLE
[@hono/vite-dev-server] Addressing Frequent Miniflare Error on Server Restart

### ISSUE THREAD

**Issue by komapotter** [honojs/vite-plugins#172]
When the server restarts upon file updates, the following message frequently appears in the browser, making it inaccessible:

```
Error! Attempted to use poisoned stub. Stubs to runtime objects must be re-created after calling `Miniflare#setOptions()` or `Miniflare#dispose()`.
```

I tried the following fix in my local project. After applying it, the error no longer occurred.

node_modules/@hono/vite-dev-server/dist/adapter/cloudflare.js

```javascript
   return {
     env: proxy.env,
     executionContext: proxy.ctx,
     onServerClose: async () => {
-      try {
-        await proxy.dispose();
-      } catch {
-      }
+      if (proxy) {
+        try {
+          await proxy.dispose();
+        } catch (error) {
+          console.error('Failed to dispose proxy:', error);
+        } finally {
+          proxy = undefined; 
+        }
+      }
     }
   };
 };
```

**Comment by yusukebe** [comment]
Hi @komapotter 

Thank you for raising the issue.

> I tried the following fix in my local project. After applying it, the error no longer occurred.

This may be a good patch for this issue. Could you create a PR with it?

**Comment by komapotter** [comment]
@yusukebe 

I have created a pull request. However, I am a beginner with TypeScript, so the content of the patch is based on an AI-generated response. 
If there are any issues, I would appreciate it if you could provide a way for me to check the changes in my local environment.

**Comment by komapotter** [comment]
> to check the changes in my local environment.

After running yarn build in the local environment, I replaced the dist directory with the one under my project and confirmed that no errors occurred during operation.
