### ISSUE TITLE
[@hono/vite-dev-server] Feauture Request: integration with universal-autorouter

### ISSUE THREAD

**Issue by rtritto** [honojs/vite-plugins#200]
Features:
- routes by index file: (`/user/index.ts` → GET `/user`)
- dynamic params with `/[<ROUTE_PARAM_NAME>].ts` syntax: (`/user/[id].ts` → GET `/user/:id`)
- dynamic method with `/(<METHOD>).ts` syntax: (`/user/(post).ts` → POST `/user`)
- grouping (implemented with a simple [sort](https://github.com/node-ecosystem/universal-autoloader/blob/9d51ea9b58afedffed8ea7887f71d8a2e6b9b059/src/utils.ts#L5-L11))
- wildcard `/[...].ts` (`/user/[...].ts` → GET `/user/*`)
- wildcard with `/@[...]` prefix (`/user/@[...].ts` → GET `/user/@*`)

Examples: [directory-structure](https://github.com/node-ecosystem/universal-autorouter?tab=readme-ov-file#directory-structure)

**Comment by yusukebe** [comment]
Hi @rtritto 

That is not in the scope of `@hono/vite-dev-server`. But for example, the [HonoX](https://github.com/honojs/honox) does.

**Comment by rtritto** [comment]
Ok, should I create same issue in [HonoX](https://github.com/honojs/honox) and/or in [Sonik](https://github.com/sonikjs/sonik)?

**Comment by yusukebe** [comment]
@rtritto 

No. HonoX already does similar things. We should not have the feature in our official rep: `github.com/honojs/*`.
