### ISSUE TITLE
[@hono/vite-dev-server] Proposal for Specialized Plugin: Cloudflare Workers/Wrangler Integration

### ISSUE THREAD

**Issue by Code-Hex** [honojs/vite-plugins#25]
Related issue: #24

@hono/vite-dev-server currently supports development servers for most edge environments. However, as we attempt to address issues specific to platforms like Cloudflare Workers/Wrangler, such concerns become more prominent. Similarly, when it comes to features tailored for other edge environments, this can lead to a situation where, for those who want to utilize the Wrangler environment, this plugin becomes overly complex.

Therefore, I have created this issue with the idea that it would be beneficial to first extract specific functionality for Cloudflare Workers/Wrangler as a dedicated plugin. I would appreciate your input on this matter.

**Comment by Code-Hex** [comment]
@navaru As linked in the related issue, I hope that the vite plugin will recognize environment variables and various infrastructure bindings specified in TOML.

I plan to use `--no-bundle` with wrangler and intend to bundle both the server and client code using vite.

**Comment by Code-Hex** [comment]
@navaru  Yes, I'm planning to use for Workers Site. So I didn't mention about it.

I know your opinion but This is the best solution for us. I will explain the reason below:

1. Our application is running on Cloudflare Workers.
2. Our application is originally only a backend, so we think it will be difficult to switch to Pages.
3. There are three workers. They are prepared as dev, staging, and production environments respectively.
4. Pages currently does not have a way to split the backend like this.
5. If you use Workers, static site uploads will be R2 or Workers Site.
6. R2 cannot upload directories using Wrangler, but Workers Site can.

> If you plan on using Cloudflare Workers for Worker Sites, this is discouraged by Cloudflare

**Comment by yusukebe** [comment]
Hi @Code-Hex!

Like @navaru, I believe you're referring to Cloudflare Pages, but it seems you're actually thinking about Cloudflare Workers.

There are several approaches to better support Cloudflare Workers:

1. Create a build plugin for Workers, similar to [this one](https://github.com/sonikjs/monorepo/tree/main/packages/adapter-cloudflare-workers).
2. Add a feature to read `wrangler.toml` options in the Vite dev-server. I'm not sure about the implementation; it might require a plugin structure?

This issue affects all platforms, including Workers and Pages:

* The runtime environment is not always ideal. For example, when creating a Pages application and using Vite in development, the environment is actually "Node.js". If you use `getRuntimeKey()` in `hono/adapter`, it returns `node`. There's also the issue of missing APIs, like Cache API and `URLPattern`, which aren't implemented in Node.js but are available in `workerd`.

Regarding this, it's worth discussing. However, I think the current pattern is fine, as Hono apps tend to be isomorphic. If we can use Bindings as they are, it should be sufficient.

**Comment by yusukebe** [comment]
I believe it would be better to implement the platform-dependent issues as a plugin structure for the dev server. If feasible, cf bindings by Miniflare could be one of the plugins. However, as mentioned above, I currently don't have a clear idea on how to implement this.

**Comment by naporin0624** [comment]
@Code-Hex @yusukebe 

I am wondering if this implementation can be achieved with reference to the vitest-miniflare-environment implementation.

The vitest-miniflare-environment reads the contents of wrangler.toml and automatically sets bindings as the output of `getMiniflareBindings`.

I was wondering if this part could be applied to a vite plugin.

I looked at how vitest-miniflare-environment gets bindings.

The vitest-miniflare-environment internally executes createMiniflareEnvironment of shared-test-environment, which passes the BindingPlugin to `MiniflareCore`. BindingPlugin is passed to `MiniflareCore`.
https://github.com/cloudflare/miniflare/blob/master/packages/shared-test-environment/src/index.ts#L27

The important part is the `getBindings` method of `MiniflareCore`. This method converts each of the bindings in wrangler.toml into a module that can be executed by cloudflare workers.
https://github.com/cloudflare/miniflare/blob/master/packages/core/src/index.ts#L365
https://github.com/cloudflare/miniflare/blob/master/packages/core/src/index.ts#L1045

I ported this getBindigns method to @hono/vite-dev-server and was able to get bindings in the fetch function.


MiniflareCore was initialized using the implementation of vitest-environment-miniflare and shared-test-environment as reference, so the code used for test is included and needs to be modified.

https://github.com/cloudflare/miniflare/blob/master/packages/vitest-environment-miniflare/src/index.ts#L86


Code for a plugin that runs `getBindings` via `MiniflareCore` and passes bindings to a `fetch` function via vite
https://github.com/naporin0624/cloudflare-workers-vite-plugin-test

**Comment by Code-Hex** [comment]
@naporin0624 Thank you for providing your idea!

@yusukebe I've tried to implement it easily in the following PR. I have confirmed that d1 and kv are working correctly.

https://github.com/honojs/vite-plugins/issues/25

I am copying a lot of code from [workers-sdk](https://github.com/cloudflare/workers-sdk). This is because some of the code defined in workers-sdk is not provided as a package. I thought it would be necessary to follow along in this regard.

**Comment by Code-Hex** [comment]
MEMO: I just noticed that we don't need to use workers-sdk code. `unstable_dev` has the option to read wrangler.toml.

**Comment by Code-Hex** [comment]
I was able to allocate some time, so I attempted to implement it using 'wrangler unstable_dev.'

The potential benefit of this approach was that I wouldn't have to keep track of updates to 'wrangler' myself. However, the `fetch` returned by the `unstable_dev` function is not part of the Worker's signature; it remains a client-side `fetch`, so it couldn't be used [here](https://github.com/honojs/vite-plugins/blob/60fef034b3ba4aeca9b21f91149d58a328d9f653/packages/dev-server/src/dev-server.ts#L81). There might have been a possibility if Cloudflare Pages' plugins were handling client-side signatures.

I will proceed with the approach outlined in [this PR](https://github.com/honojs/vite-plugins/pull/26).

**Comment by cloudkite** [comment]
BTW not sure if you are already aware but this should now be much easier to implement as there’s a new getBindingsProxy function in Miniflare https://github.com/cloudflare/workers-sdk/pull/4523 so could be a great opportunity to simplify and remove a lot of code

**Comment by izznatsir** [comment]
getBindingsProxy has been released to stable version.

**Comment by Code-Hex** [comment]
I will try to fix this using the API!

**Comment by yusukebe** [comment]
Hey @Code-Hex 

Please wait a minute!

Now I am thinking of creating a `@hono/vite-cloudflare` with `getBindingsProxy`. It would cover not only Workers but also Pages. With it I can deprecate the current `@hono/vite-cloudflare-pages`.

I am going to create that draft, and I would like @Code-Hex to review it.

**Comment by Code-Hex** [comment]
@yusukebe sounds good!
Thank you so much!

**Comment by yusukebe** [comment]
I need your help, but since this is a Cloudflare feature, let me, a Cloudflare employee, do it:)

**Comment by yusukebe** [comment]
I think we should wait a little longer on this issue.

The new version, 5.1 of Vite has been released.

https://vitejs.dev/blog/announcing-vite5-1.html

With this version, Vite is now experimentally supporting Runtime other than Node.js. This means that Miniflare/workerd environments can be integrated into Vite using Vite's API. We Cloudflare may make Miniflare/wokred runtime official. It is more efficient and preferred than having each framework support Cloudflare individually.

So, let's wait and see.

**Comment by yusukebe** [comment]
Hey @Code-Hex  and others!

Now, we can use the new API [`getPlatformProxy()` in Wrangler](https://developers.cloudflare.com/workers/wrangler/api/#getplatformproxy). This will automatically read variables from `wrangler.toml`. You can integrate it into `@hono/vite-dev-server` without creating a plugin. Try it!

```ts
import devServer from '@hono/vite-dev-server'
import { defineConfig } from 'vite'
import { getPlatformProxy } from 'wrangler'

export default defineConfig(async () => {
  const { env, dispose } = await getPlatformProxy()
  return {
    plugins: [
      devServer({
        env,
        plugins: [
          {
            onServerClose: dispose
          }
        ]
      })
    ]
  }
})
```

**Comment by Code-Hex** [comment]
I close this PR once!
continue discussion on the issue #24
